const extmime: {
  [key: string]: string;
} = {
  '3ds': 'image/x-3ds',
  '3g2': 'video/3gpp2',
  '3gp': 'video/3gpp',
  '7z': 'application/x-7z-compressed',
  aac: 'audio/x-aac',
  abw: 'application/x-abiword',
  ace: 'application/x-ace-compressed',
  adp: 'audio/adpcm',
  aif: 'audio/x-aiff',
  aifc: 'audio/x-aiff',
  aiff: 'audio/x-aiff',
  apk: 'application/vnd.android.package-archive',
  asf: 'video/x-ms-asf',
  asx: 'video/x-ms-asf',
  atom: 'application/atom+xml',
  au: 'audio/basic',
  avi: 'video/x-msvideo',
  bat: 'application/x-msdownload',
  bmp: 'image/bmp',
  btif: 'image/prs.btif',
  bz: 'application/x-bzip',
  bz2: 'application/x-bzip2',
  caf: 'audio/x-caf',
  cgm: 'image/cgm',
  cmx: 'image/x-cmx',
  com: 'application/x-msdownload',
  conf: 'text/plain',
  css: 'text/css',
  csv: 'text/csv',
  dbk: 'application/docbook+xml',
  deb: 'application/x-debian-package',
  def: 'text/plain',
  djv: 'image/vnd.djvu',
  djvu: 'image/vnd.djvu',
  dll: 'application/x-msdownload',
  dmg: 'application/x-apple-diskimage',
  doc: 'application/msword',
  docm: 'application/vnd.ms-word.document.macroenabled.12',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  dot: 'application/msword',
  dotm: 'application/vnd.ms-word.template.macroenabled.12',
  dotx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  dra: 'audio/vnd.dra',
  dtd: 'application/xml-dtd',
  dts: 'audio/vnd.dts',
  dtshd: 'audio/vnd.dts.hd',
  dvb: 'video/vnd.dvb.file',
  dwg: 'image/vnd.dwg',
  dxf: 'image/vnd.dxf',
  ecelp4800: 'audio/vnd.nuera.ecelp4800',
  ecelp7470: 'audio/vnd.nuera.ecelp7470',
  ecelp9600: 'audio/vnd.nuera.ecelp9600',
  emf: 'application/x-msmetafile',
  emz: 'application/x-msmetafile',
  eol: 'audio/vnd.digital-winds',
  epub: 'application/epub+zip',
  exe: 'application/x-msdownload',
  f4v: 'video/x-f4v',
  fbs: 'image/vnd.fastbidsheet',
  fh: 'image/x-freehand',
  fh4: 'image/x-freehand',
  fh5: 'image/x-freehand',
  fh7: 'image/x-freehand',
  fhc: 'image/x-freehand',
  flac: 'audio/x-flac',
  fli: 'video/x-fli',
  flv: 'video/x-flv',
  fpx: 'image/vnd.fpx',
  fst: 'image/vnd.fst',
  fvt: 'video/vnd.fvt',
  g3: 'image/g3fax',
  gif: 'image/gif',
  h261: 'video/h261',
  h263: 'video/h263',
  h264: 'video/h264',
  heif: 'image/heif',
  heic: 'image/heic',
  htm: 'text/html',
  html: 'text/html',
  ico: 'image/x-icon',
  ief: 'image/ief',
  iso: 'application/x-iso9660-image',
  jpe: 'image/jpeg',
  jpeg: 'image/jpeg',
  jpg: 'image/jpeg',
  jpgm: 'video/jpm',
  jpgv: 'video/jpeg',
  jpm: 'video/jpm',
  json: 'application/json',
  jsonml: 'application/jsonml+json',
  kar: 'audio/midi',
  ktx: 'image/ktx',
  list: 'text/plain',
  log: 'text/plain',
  lvp: 'audio/vnd.lucent.voice',
  m13: 'application/x-msmediaview',
  m14: 'application/x-msmediaview',
  m1v: 'video/mpeg',
  m21: 'application/mp21',
  m2a: 'audio/mpeg',
  m2v: 'video/mpeg',
  m3a: 'audio/mpeg',
  m3u: 'audio/x-mpegurl',
  m3u8: 'application/vnd.apple.mpegurl',
  m4a: 'audio/mp4',
  m4u: 'video/vnd.mpegurl',
  m4v: 'video/x-m4v',
  mdi: 'image/vnd.ms-modi',
  mid: 'audio/midi',
  midi: 'audio/midi',
  mj2: 'video/mj2',
  mjp2: 'video/mj2',
  mk3d: 'video/x-matroska',
  mka: 'audio/x-matroska',
  mks: 'video/x-matroska',
  mkv: 'video/x-matroska',
  mmr: 'image/vnd.fujixerox.edmics-mmr',
  mng: 'video/x-mng',
  mov: 'video/quicktime',
  movie: 'video/x-sgi-movie',
  mp2: 'audio/mpeg',
  mp21: 'application/mp21',
  mp2a: 'audio/mpeg',
  mp3: 'audio/mpeg',
  mp4: 'video/mp4',
  mp4a: 'audio/mp4',
  mp4s: 'application/mp4',
  mp4v: 'video/mp4',
  mpe: 'video/mpeg',
  mpeg: 'video/mpeg',
  mpg: 'video/mpeg',
  mpg4: 'video/mp4',
  mpga: 'audio/mpeg',
  mpkg: 'application/vnd.apple.installer+xml',
  msi: 'application/x-msdownload',
  mvb: 'application/x-msmediaview',
  mxf: 'application/mxf',
  mxml: 'application/xv+xml',
  mxu: 'video/vnd.mpegurl',
  npx: 'image/vnd.net-fpx',
  odb: 'application/vnd.oasis.opendocument.database',
  odc: 'application/vnd.oasis.opendocument.chart',
  odf: 'application/vnd.oasis.opendocument.formula',
  odft: 'application/vnd.oasis.opendocument.formula-template',
  odg: 'application/vnd.oasis.opendocument.graphics',
  odi: 'application/vnd.oasis.opendocument.image',
  odm: 'application/vnd.oasis.opendocument.text-master',
  odp: 'application/vnd.oasis.opendocument.presentation',
  ods: 'application/vnd.oasis.opendocument.spreadsheet',
  odt: 'application/vnd.oasis.opendocument.text',
  oga: 'audio/ogg',
  ogg: 'audio/ogg',
  ogv: 'video/ogg',
  ogx: 'application/ogg',
  otc: 'application/vnd.oasis.opendocument.chart-template',
  otg: 'application/vnd.oasis.opendocument.graphics-template',
  oth: 'application/vnd.oasis.opendocument.text-web',
  oti: 'application/vnd.oasis.opendocument.image-template',
  otp: 'application/vnd.oasis.opendocument.presentation-template',
  ots: 'application/vnd.oasis.opendocument.spreadsheet-template',
  ott: 'application/vnd.oasis.opendocument.text-template',
  oxt: 'application/vnd.openofficeorg.extension',
  pbm: 'image/x-portable-bitmap',
  pct: 'image/x-pict',
  pcx: 'image/x-pcx',
  pdf: 'application/pdf',
  pgm: 'image/x-portable-graymap',
  pic: 'image/x-pict',
  plb: 'application/vnd.3gpp.pic-bw-large',
  png: 'image/png',
  pnm: 'image/x-portable-anymap',
  pot: 'application/vnd.ms-powerpoint',
  potx: 'application/vnd.openxmlformats-officedocument.presentationml.template',
  ppm: 'image/x-portable-pixmap',
  pps: 'application/vnd.ms-powerpoint',
  ppsx: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  psb: 'application/vnd.3gpp.pic-bw-small',
  psd: 'image/vnd.adobe.photoshop',
  pvb: 'application/vnd.3gpp.pic-bw-var',
  pya: 'audio/vnd.ms-playready.media.pya',
  pyv: 'video/vnd.ms-playready.media.pyv',
  qt: 'video/quicktime',
  ra: 'audio/x-pn-realaudio',
  ram: 'audio/x-pn-realaudio',
  ras: 'image/x-cmu-raster',
  rgb: 'image/x-rgb',
  rip: 'audio/vnd.rip',
  rlc: 'image/vnd.fujixerox.edmics-rlc',
  rmi: 'audio/midi',
  rmp: 'audio/x-pn-realaudio-plugin',
  s3m: 'audio/s3m',
  sgi: 'image/sgi',
  sgm: 'text/sgml',
  sgml: 'text/sgml',
  sid: 'image/x-mrsid-image',
  sil: 'audio/silk',
  sldx: 'application/vnd.openxmlformats-officedocument.presentationml.slide',
  smv: 'video/x-smv',
  snd: 'audio/basic',
  spx: 'audio/ogg',
  srt: 'application/x-subrip',
  sub: 'text/vnd.dvb.subtitle',
  svg: 'image/svg+xml',
  svgz: 'image/svg+xml',
  swf: 'application/x-shockwave-flash',
  tcap: 'application/vnd.3gpp2.tcap',
  text: 'text/plain',
  tga: 'image/x-tga',
  tif: 'image/tiff',
  tiff: 'image/tiff',
  torrent: 'application/x-bittorrent',
  tsv: 'text/tab-separated-values',
  ttl: 'text/turtle',
  txt: 'text/plain',
  udeb: 'application/x-debian-package',
  uva: 'audio/vnd.dece.audio',
  uvg: 'image/vnd.dece.graphic',
  uvh: 'video/vnd.dece.hd',
  uvi: 'image/vnd.dece.graphic',
  uvm: 'video/vnd.dece.mobile',
  uvp: 'video/vnd.dece.pd',
  uvs: 'video/vnd.dece.sd',
  uvu: 'video/vnd.uvvu.mp4',
  uvv: 'video/vnd.dece.video',
  uvva: 'audio/vnd.dece.audio',
  uvvg: 'image/vnd.dece.graphic',
  uvvh: 'video/vnd.dece.hd',
  uvvi: 'image/vnd.dece.graphic',
  uvvm: 'video/vnd.dece.mobile',
  uvvp: 'video/vnd.dece.pd',
  uvvs: 'video/vnd.dece.sd',
  uvvu: 'video/vnd.uvvu.mp4',
  uvvv: 'video/vnd.dece.video',
  viv: 'video/vnd.vivo',
  vob: 'video/x-ms-vob',
  wav: 'audio/x-wav',
  wax: 'audio/x-ms-wax',
  wbmp: 'image/vnd.wap.wbmp',
  wdp: 'image/vnd.ms-photo',
  weba: 'audio/webm',
  webm: 'video/webm',
  webp: 'image/webp',
  wm: 'video/x-ms-wm',
  wma: 'audio/x-ms-wma',
  wmf: 'application/x-msmetafile',
  wmv: 'video/x-ms-wmv',
  wmx: 'video/x-ms-wmx',
  wvx: 'video/x-ms-wvx',
  xap: 'application/x-silverlight-app',
  xbm: 'image/x-xbitmap',
  xht: 'application/xhtml+xml',
  xhtml: 'application/xhtml+xml',
  xhvml: 'application/xv+xml',
  xif: 'image/vnd.xiff',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  xltx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
  xm: 'audio/xm',
  xml: 'application/xml',
  xop: 'application/xop+xml',
  xpl: 'application/xproc+xml',
  xpm: 'image/x-xpixmap',
  xsl: 'application/xml',
  xslt: 'application/xslt+xml',
  xspf: 'application/xspf+xml',
  xvm: 'application/xv+xml',
  xvml: 'application/xv+xml',
  xwd: 'image/x-xwindowdump',
  zip: 'application/zip'
};
const ext: {
  [key: string]: string;
} = {};
export function filemime(name: string) {
  var fext = fileext(name);
  return extmime[fext] || 'application/octet-stream';
}

export function filetype(name: string): string {
  var fext = fileext(name);
  if (ext[fext]) {
    return ext[fext][1];
  } else if (fext && fext.length > 1) {
    return '%1 File'.replace('%1', fext.toUpperCase());
  } else {
    return 'File';
  }
}
export function fileext(name: string, uppercase: boolean = false, iknowwhatimdoing: boolean = false) {
  name = String(name || '');
  if (!name) {
    name = 'unknown';
  }

  var ext = name.substr(name.lastIndexOf('.') + 1);
  if (ext === name) {
    ext = '';
  } else if (!iknowwhatimdoing) {
    ext = ext.replace(/<[^>]*>/g, '').replace(/[^\w+]/g, '');

    if (ext.length > 9) {
      ext = ext.substr(0, 9);
    }
  }

  return uppercase ? ext.toUpperCase() : ext.toLowerCase();
}
